### ISSUE TITLE
cannot port forward

### ISSUE THREAD

**Issue by arshad2374** [micahmo/WgServerforWindows#44]
please give me full guide about port forwarding on wg server on windows

**Comment by micahmo** [comment]
Hey @arshad2374, I'm afraid I don't completely understand your question. The main port forwarding that I'm aware of in reference to WireGuard is from your router to your WireGuard server machine (regardless of Window or Linux).

Most people with home internet will have all of their personal devices behind NAT, meaning that each device gets assigned an internal IP address, and your whole network is represented by one external IP address (aka WAN address), managed by your router. In order to connect to your home network from outside, you must direct requests to your WAN IP. However, if you want your requests to be forwarded to a particular device (in this case, the device running the WireGuard server), you need to specify a port so that your router knows how to direct the request.

WireGuard normally uses port `51820`, although that's customizable. Whichever port you pick, you should forward it from your router to your WireGuard server machine. Unfortunately, that process will be different depending on your router. The README has one example for FiOS routers, pictured below, if it helps. But you'll probably be better off Googling: `<your router brand> port forwarding`.

![image](https://user-images.githubusercontent.com/7417301/168449923-6df77175-cf94-4c55-8065-48d4552915a4.png)

I apologize if you were referring to another kind of port forwarding that I am unaware of!

**Comment by micahmo** [comment]
@arshad2374, did you get the information you were looking for? If so, I will close this issue.

**Comment by micahmo** [comment]
I am going to close this issue as no further questions or details have been provided by the submitter.
