### ISSUE TITLE
Remove the need of private keys for configuring clients.

### ISSUE THREAD

**Issue by Lehmaning** [micahmo/WgServerforWindows#47]
In common situation, only public keys are required in the config for clients. However, the private key of clients is needed in WS4W. It's weird. Could it be removed or be set as optional?

**Comment by micahmo** [comment]
Hi @Lehmaning! If I'm understanding your request correctly, it has already been implemented, as described in #26, and released in [v1.7.1](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.1) (check the release notes).

Here you can see I have a client configuration with no private key, and there is no validation error.

![image](https://user-images.githubusercontent.com/7417301/169858095-8c2f5450-5629-4d98-bb2a-faf2fd90eaa4.png)

Just a note that you _do_ have to generate the private key at least one, because...
1. The client needs the private key
2. The server needs the public key, which is generated from the private key

So your workflow would be...
1. Generate private key, public key, and (optionally) preshared key
2. Export client configuration (QR code or file) and import into client device
3. Delete private key from WS4W app and save client config

Please verify that you have the latest version, try the steps above, and let me know if it works for you. Thanks!

**Comment by Lehmaning** [comment]
> Hi @Lehmaning! If I'm understanding your request correctly, it has already been implemented, as described in #26, and released in [v1.7.1](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.1) (check the release notes).
> 
> Here you can see I have a client configuration with no private key, and there is no validation error.
> 
> ![image](https://user-images.githubusercontent.com/7417301/169858095-8c2f5450-5629-4d98-bb2a-faf2fd90eaa4.png)
> 
> Just a note that you _do_ have to generate the private key at least one, because...
> 
>     1. The client needs the private key
> 
>     2. The server needs the public key, which is generated from the private key
> 
> 
> So your workflow would be...
> 
>     1. Generate private key, public key, and (optionally) preshared key
> 
>     2. Export client configuration (QR code or file) and import into client device
> 
>     3. Delete private key from WS4W app and save client config
> 
> 
> Please verify that you have the latest version, try the steps above, and let me know if it works for you. Thanks!
Oh, I see. That's great. Sorry for my poor English 🥲
