### ISSUE TITLE
Cannot specify a client with IPv6 address 

### ISSUE THREAD

**Issue by qwer1304** [micahmo/WgServerforWindows#54]
Hi,

In version 2.0.1.0 (ran as Administrator) I cannot specify in the Client an IPv6 address.

If the server's address is an IPv6 (e.g., fd4d:b189:9674::1/64) then Generate from Server button doesn't work and the program hangs.

If I manually enter an IPv6 address in Client (e.g., fd4d:b189:9674::2/64) then the box remains red. If I save this I get:
One or more clients has missing or incorrect configuration.

There's also a hint for Address field that an address should be a SINGLE address, but this is incorrect since I could provide BOTH an IPv4 and an IPv6 address.

Thx

**Comment by micahmo** [comment]
Hey, thanks for the report! This should be pretty straightforward to fix.

Remember that you can always update the client config directly (in the client app or in the exported file) in case there are any limitations in WS4W. 😊

**Comment by micahmo** [comment]
Hi @qwer1304,

> If the server's address is an IPv6 (e.g., fd4d:b189:9674::1/64) then Generate from Server button doesn't work and the program hangs.

This issue has been fixed in [2.0.2](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.2).

> If I manually enter an IPv6 address in Client (e.g., fd4d:b189:9674::2/64) then the box remains red. If I save this I get:
One or more clients has missing or incorrect configuration.

I apologize that I didn't catch this sooner, but there's no bug here. You're entering an IP range, as indicated by the trailing `/64`. Notice that it's in the same format as the server's address range. Instead, you want to specify a single IP for the client, such as `fd4d:b189:9674::2`. In fact, with the fixed version, you'll see pressing Generate from Server populates exactly that value given your example. The alternative is to use the `/128` suffix, which is a network range with only one valid address. 😊

> There's also a hint for Address field that an address should be a SINGLE address, but this is incorrect since I could provide BOTH an IPv4 and an IPv6 address.

Good catch. The hint and the functionality have been updated to handle multiple IP addresses. This is also in [2.0.2](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.2).
