### ISSUE TITLE
About the minimum version of windows server supported by this software.

### ISSUE THREAD

**Issue by tiny-andr** [micahmo/WgServerforWindows#65]
Hi !
thank you for sharing this source!
 If I choose windows serve as the system of WgServerforWindows, then what minimum version of WinServer can I choose? According to my friend's test, he said that windows server2008R2 will prompt that the version is too low.

**Comment by micahmo** [comment]
Hi @tiny-andr, I haven't specified a minimum supported version because I can't promise the amount of testing and validation that's required to officially support different versions of Windows. My development and testing has been on Windows 10 (with a few different variants for feature support). But I hesitate to say Win 10 is the min version in case it works fine on older versions. It sounds like 2008 is past that threshold (no surprise 😄). However, feel free to share the error your friend got if you like.

**Comment by micahmo** [comment]
Hi @tiny-andr, I have added a [section to the README](https://github.com/micahmo/WgServerforWindows#compatibility) about Windows compatibility. This is based on my own limited testing and feedback here, so if you have any additional info to provide, let me know!

**Comment by tiny-andr** [comment]
Thanks.！My friend has upgraded to windows server2019. This problem is not a problem for now. For those who are still using 2008, I think we should skip them~
