### ISSUE TITLE
Can't enable internet sharing after enabling NAT

### ISSUE THREAD

**Issue by dbrannon79** [micahmo/WgServerforWindows#66]
following the setup steps once NAT is enabled, I cannot enable internet sharing or persistent sharing, both buttons are greyed out.   I can enable internet sharing manually by opening the network connections properties.   reopening the Wg Server app shows sharing is enabled but not persistent.  

I have gone into regedit and changed HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\SharedAccess\EnableRebootPersistConnection from 0 to 1 and changed "Internet Connection Sharing" in services from manual to automatic.  so far with a restart of windows it all seems to be working on a remote client, but the app still shows persistent sharing  is disabled with the button greyed out. 

This is on the most recent win 10 updates on 22H2.   is there a manual setting I am missing or can the app be updated to allow the buttons to work?

**Comment by micahmo** [comment]
Hi @dbrannon79,

The app is working as expected. NAT Routing and Internet Sharing are two alternative options for accomplishing the same thing. Once you enable one, the other will become unavailable. That's why they appear grouped as the same step rather than sequential steps. The reason both options exist is because NAT Routing is not supported on all versions of Windows.

Please see [this section](https://github.com/micahmo/WgServerforWindows#routing) of the README. I've highlighted the relevant parts.

![image](https://user-images.githubusercontent.com/7417301/201520277-09856bba-5fe0-41e4-a4d7-f07a1e92325b.png)

Since your remote client is working, I will close this issue. Feel free to reopen it if you have any more questions.
