### ISSUE TITLE
2.0.4: Can not generate client's ip address from server

### ISSUE THREAD

**Issue by Weegley** [micahmo/WgServerforWindows#70]
When pressing correspondent button following error occurs

[![](https://s1.hostingkartinok.com/uploads/images/2023/01/7bd3a00da1757d6061a761e480ec2264.png)](https://s1.hostingkartinok.com/uploads/images/2023/01/705809f8977b92174d1e59c072538e76.png)  

2.0.3 version works well

**Comment by micahmo** [comment]
What's the value of your server address?

CC: @xeptore

**Comment by Weegley** [comment]
Now it's 172.16.0.1/24
First i tried 10.something which was default on fresh install.
Also tried 2.0.2 and 2.0.3 - they generate like a charm from 172.16.0.1/24

**Comment by micahmo** [comment]
Thanks! Can you press Copy Details and paste the output here?

**Comment by Weegley** [comment]
It gives another error:
[![](https://s1.hostingkartinok.com/uploads/images/2023/01/aaa301a0bd0f0e13f4820e58ed7fcc0f.png)](https://s1.hostingkartinok.com/uploads/images/2023/01/59b542f7c27f627769152258ac5d6056.png)  
BUT, if i first enter ANYTHING in that field and press "generate from server" then it works.

**Comment by xeptore** [comment]
Hey @micahmo, I guess the issue is with [these 2 lines](https://github.com/micahmo/WgServerforWindows/blob/main/WgServerforWindows/Models/ClientConfiguration.cs#L60-L61), which when the input field is empty, the `prop.Value` is (strangely) `null`, and calling the `.Split()` causes a null reference error. And that's why @Weegley mentioned that having it filled with "something" resolves the issue. I suggest first having a default value for `prop.Value`, [as I did in my PR](https://github.com/micahmo/WgServerforWindows/pull/67/files#diff-b136fc132e45ed07c11c485c5a818f7f4ad24cc66cd1a36904e7d8a30a8c418aR454), like `var inputValue = prop.Value ?? "";` in the beginning of the validation fiunction, and use the `inputValue` in the rest of the function. Also, I can suggest using the `StringSplitOptions.RemoveEmptyEntries` option for all `string.Split()` calls, as I did in that linko too, as it eliminates the need for trimming IP addresses when they're separated by comma spaces, e.g., `, `.

Hope that it helps.

**Comment by xeptore** [comment]
> It gives another error:

@micahmo, also for this one I found this SO solution: https://stackoverflow.com/a/69081 (although I'm currently laughing at how/what MS is doing over there 😄).

I'm not sure whether the call to the clipboard in the application is done by you in case of unhandled exceptions, or it's the default behavior of .NET, but that might be helpful.

**Comment by micahmo** [comment]
@Weegley This should be fixed in [2.0.5](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.5). Can you give it a try? Thanks!

**Comment by Weegley** [comment]
Yep, will do a bit later

**Comment by Weegley** [comment]
Yes. Client ip (fill up?) working good now. But can't say about clipboard.

**Comment by micahmo** [comment]
Thanks for the update! No worries about the clipboard issue, that's just for troubleshooting anyway.
