### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by timbolin** [micahmo/WgServerforWindows#93]
this little tool made my life SO much easier. how can i send a donation as a token of my appreciation?

**Comment by micahmo** [comment]
Dupe of #32 😄

In all seriousness, that's very kind of you. Since I've gotten multiple requests to do this, I have added a "Buy Me a Coffee" link to my [profile](https://github.com/micahmo). Please never feel obligated to donate! I maintain this project in my free time and can't promise any support. 😊
